resies/config/routes.rb
Rails.application.routes.draw do

  resources :historia
  resources :questions
  resources :formularios
  resources :question
  resources :instituciones
  devise_for :users, controllers: {:registrations => 'user/registrations', :confirmations =>'user/confirmations'}
  root to: 'welcome#index'

  get 'manual/', to: 'manual#index'

  post'formularios/historia/:id',to:'formularios#historial' , as: 'historial'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

resies/app/models/alternativa.rb
class Alternativa < ApplicationRecord
  belongs_to :question
end

resies/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

resies/app/models/cat.rb
class Cat < ApplicationRecord
  has_many :subcats
end

resies/app/models/formulario.rb
class Formulario < ApplicationRecord

  belongs_to :user

end

resies/app/models/historium.rb
class Historium < ApplicationRecord
end

resies/app/models/institucione.rb
class Institucione < ApplicationRecord
  belongs_to :tipoinstitucione
  belongs_to :tiporelacione
  belongs_to :region

  has_attached_file :avatar, styles: { medium: "300x300", thumb: "50x50" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

resies/app/models/paise.rb
class Paise < ApplicationRecord
  has_many :regions
end

resies/app/models/question.rb
class Question < ApplicationRecord
  has_many :alternativas,  dependent: :destroy,  inverse_of: :question
  accepts_nested_attributes_for :alternativas,  allow_destroy: true
  belongs_to :subcat
end

resies/app/models/region.rb
class Region < ApplicationRecord
  has_many :instituciones
  belongs_to :paise
end

resies/app/models/subcat.rb
class Subcat < ApplicationRecord
  has_many :questions
  belongs_to :cat
end

resies/app/models/tipoinstitucione.rb
class Tipoinstitucione < ApplicationRecord
  has_many :instituciones
end

resies/app/models/tiporelacione.rb
class Tiporelacione < ApplicationRecord
  has_many :instituciones
end

resies/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :formularios
end

resies/app/controllers/historia_controller.rb
class HistoriaController < ApplicationController
  before_action :set_historium, only: [:show, :edit, :update, :destroy]

  # GET /historia
  # GET /historia.json
  def index
    @historia = Historium.all
    @instituciones = Institucione.all
    respond_to do |format|
      format.html
      format.json
      format.pdf do
        render pdf: "Reporte RESIES",
         disposition: 'attachment',
        template: "historia/index.html.erb"
      end
    end
  end

  # GET /historia/1
  # GET /historia/1.json
  def show
    @questions = Question.all
    @formularios = Formulario.all
    @instituciones = Institucione.all
    respond_to do |format|
      format.html
      format.json
      format.pdf do
        render pdf: "Reporte RESIES",
         disposition: 'attachment',
        template: "historia/show.html.erb"

      end


    end

  end

  # GET /historia/new
  def new
    @historium = Historium.new
    @formularios = Formulario.all
    @instituciones = Institucione.all
  end

  # GET /historia/1/edit
  def edit
    @questions = Question.all
    @formularios = Formulario.all
    @instituciones = Institucione.all
  end

  # POST /historia
  # POST /historia.json
  def create
    @historium = Historium.new(historium_params)

    respond_to do |format|
      if @historium.save
        format.html { redirect_to @historium, notice: 'Historium was successfully created.' }
        format.json { render :show, status: :created, location: @historium }
      else
        format.html { render :new }
        format.json { render json: @historium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historia/1
  # PATCH/PUT /historia/1.json
  def update
    respond_to do |format|
      if @historium.update(historium_params)
        format.html { redirect_to formulario_path, notice: 'Historium was successfully updated.' }
        format.json { render :index, status: :ok, location: formulario_path }
      else
        format.html { render :edit }
        format.json { render json: @historium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historia/1
  # DELETE /historia/1.json
  def destroy
    @historium.destroy
    respond_to do |format|
      format.html { redirect_to historia_url, notice: 'Historium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historium
      @historium = Historium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def historium_params
      params.require(:historium).permit(:historiaid,:mesfecha,:global, :gobpon, :gobbru, :gob1pon, :gob1bru, :gob2pon, :gob2bru, :gob3pon, :gob3bru, :gob4pon, :gob4bru, :gob5pon, :gob5bru, :gob6pon, :gob6bru, :cupon, :cubru, :cu1pon, :cu1bru, :cu2pon, :cu2bru, :cu3pon, :cu3bru, :cu4pon, :cu4bru, :cu5pon, :cu5bru, :cu6pon, :cu6bru, :cu7pon, :cu7bru, :acpon, :acbru, :ac1pon, :ac1bru, :ac2pon, :ac2bru, :ac3pon, :ac3bru, :ac4pon, :ac4bru, :ac5pon, :ac5bru, :ac6pon, :ac6bru, :ac7pon, :ac7bru, :ac8pon, :ac8bru, :gcpon, :gcbru, :gc1pon, :gc1bru, :gc2pon, :gc2bru, :gc3pon, :gc3bru, :gc4pon, :gc4bru, :gc5pon, :gc5bru, :gc6pon, :gc6bru, :gc7pon, :gc7bru, :gc8pon, :gc8bru, :gc9pon, :gc9bru, :gc10pon, :gc10bru, :gc11pon, :gc11bru, :gc12pon, :gc12bru, :gc13pon, :gc13bru, :gc14pon, :gc14bru, :gc15pon, :gc15bru, :rspon, :rsbru, :rs1pon, :rs1bru, :rs2pon, :rs2bru, :rs3pon, :rs3bru, :rs4pon, :rs4bru, :rs5pon, :rs5bru, :rs6pon, :rs6bru, :rs7pon, :rs7bru, :rs8pon, :rs8bru, :rs9pon, :rs9bru)
    end
end

resies/app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def javascript(*files)
  content_for(:head) { javascript_include_tag(*files) }
  end

def stylesheet(*files)
  content_for(:head) { stylesheet_link_tag(*files) }
end
def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end




end

resies/app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

resies/app/helpers/formularios_helper.rb
module FormulariosHelper
end

resies/app/helpers/historia_helper.rb
module HistoriaHelper
end

resies/app/helpers/instituciones_helper.rb
module InstitucionesHelper
end

resies/app/helpers/manual_helper.rb
module ManualHelper
end

resies/app/helpers/questions_helper.rb
module QuestionsHelper
end

resies/app/helpers/welcome_helper.rb
module WelcomeHelper
end

resies/app/views/historia/edit.html.erb
<%= render 'form', historium: @historium %>

<%= link_to 'Show', @historium %> |
<%= link_to 'Back', historia_path %>

resies/app/views/historia/index.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<%= wicked_pdf_stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" %>
<%= wicked_pdf_javascript_include_tag "//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"%>
<%= wicked_pdf_javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"%>
<!------ Include the above in your HEAD tag ---------->
<%= stylesheet_link_tag "formulariomostrar.css" %>
<%= wicked_pdf_stylesheet_link_tag "formulariomostrar.css" %>
<%= javascript_include_tag "http://www.google.com/jsapi" %>
<div class="container" style=" font-family: monospace; margin-top: 60px;">
    <div class="row">
        <div class="col-12">
            <div class="card" style="background-color: #fff">
                    <div class="row pb-5 p-5" style="font-size: 12pt">
                        <div class="col-md-12">

                            <%= wicked_pdf_image_tag image_url('/assets/red.jpg'), height: '120', width: '320'  %>
                          </br>
                          </br>
                          <div class="col-md-11 text-center" >
                              <p class="font-weight-bold mb-1" style="font-size: 18pt; font-family: monospace;"> RESIES "REPORTE Y EVALUACION DE LA SUSTENTABILIDAD DE INSTITUCIONES DE EDUCACION SUPERIOR"</p>
                          </div>
                        </div>
                    </div>
             </div>
             <div class="card" >
                  <div class="row pb-5 p-5" style="font-size: 12pt">

                  <div class="col-md-12">
                  </br><p class="font-weight-bold mb-1" style="font-size: 25pt; font-family: monospace;">Resultado Global</p></br>
                      <div class="col-md-12">
                        <div class="col-md-12 text-center">
                        </br></br>
                          <table class="table text-center" style="font-size: 10pt; align: center">
                            <%= line_chart Historium.where(historiaid: current_user.id).order(mesfecha: :asc).pluck(:mesfecha, :global) ,xtitle: "N° de encuesta", ytitle: "Puntaje Global", width: "950px", height: "300px" , discrete: true , colors: ["#2F4F4F"],  label: "Puntaje"%>
                          </table>
                        </div>
                      </div>
                  </div>
                 </div>

              <div class="panel-heading" style="background-color:  #fff">
                   <p class="panel-title"  style="font-size: 25pt; font-family: monospace;" >Resultados por Categoria </p>
              </div>

              <div class="panel-heading" style="background-color:  #d0dffa">
                     <p class="font-weight-bold mb-2"  style="font-size: 18pt; font-family: monospace;" >Gobernanza y Seguimiento </p>
                </div>
                <div class="row pb-5 p-5" style="font-size: 12pt">
                <div class="col-md-12">
                    <div class="col-md-12">
                      <div class="col-md-12 text-center">
                      </br></br>
                        <table class="table text-center" style="font-size: 10pt; align: center">
                          <%= line_chart Historium.where(historiaid: current_user.id).order(mesfecha: :asc).pluck(:mesfecha, :gobbru) ,xtitle: "N° de encuesta", ytitle: "Puntaje ", width: "950px", height: "300px" , discrete: true , colors: ["#2669e2"],  label: "Puntaje"%>
                        </table>
                      </div>
                    </div>
                </div>
               </div>
</br></br>
                 <div class="panel-heading" style="background-color:  #ffd18c">
                        <p class="font-weight-bold mb-2"  style="font-size: 18pt; font-family: monospace;" >Cultura Sustentable </p>
                   </div>
                   <div class="row pb-5 p-5" style="font-size: 12pt">
                   <div class="col-md-12">
                       <div class="col-md-12">
                         <div class="col-md-12 text-center">
                         </br></br>
                           <table class="table text-center" style="font-size: 10pt; align: center">
                             <%= line_chart Historium.where(historiaid: current_user.id).order(mesfecha: :asc).pluck(:mesfecha, :cubru) ,xtitle: "N° de encuesta", ytitle: "Puntaje ", width: "950px", height: "300px" , discrete: true , colors: ["#e59824"],  label: "Puntaje"%>
                           </table>
                         </div>
                       </div>
                   </div>
                  </div>

                  <div class="panel-heading" style="background-color:  #dabcf6">
                         <p class="font-weight-bold mb-2"  style="font-size: 18pt; font-family: monospace;" >Academia </p>
                    </div>
                    <div class="row pb-5 p-5" style="font-size: 12pt">
                    <div class="col-md-12">
                        <div class="col-md-12">
                          <div class="col-md-12 text-center">
                          </br></br>
                            <table class="table text-center" style="font-size: 10pt; align: center">
                              <%= line_chart Historium.where(historiaid: current_user.id).order(mesfecha: :asc).pluck(:mesfecha, :acbru) ,xtitle: "N° de encuesta", ytitle: "Puntaje ", width: "950px", height: "300px" , discrete: true , colors: ["#7b2dc4"],  label: "Puntaje"%>
                            </table>
                          </div>
                        </div>
                    </div>
                   </div>

                  <div class="panel-heading" style="background-color:  #ccffdd">
                         <p class="font-weight-bold mb-2"  style="font-size: 18pt; font-family: monospace;" >Gestion de Campus </p>
                    </div>
                    <div class="row pb-5 p-5" style="font-size: 12pt">
                    <div class="col-md-12">
                        <div class="col-md-12">
                          <div class="col-md-12 text-center">
                          </br></br>
                            <table class="table text-center" style="font-size: 10pt; align: center">
                              <%= line_chart Historium.where(historiaid: current_user.id).order(mesfecha: :asc).pluck(:mesfecha, :gcbru) ,xtitle: "N° de encuesta", ytitle: "Puntaje ", width: "950px", height: "300px" , discrete: true , colors: ["#3aaa5f"],  label: "Puntaje"%>
                            </table>
                          </div>
                        </div>
                    </div>
                   </div>

                   <div class="panel-heading" style="background-color:  #e6f7ff">
                          <p class="font-weight-bold mb-2"  style="font-size: 18pt; font-family: monospace;" >Responsabilidad Social </p>
                     </div>
                     <div class="row pb-5 p-5" style="font-size: 12pt">
                     <div class="col-md-12">
                         <div class="col-md-12">
                           <div class="col-md-12 text-center">
                           </br></br>
                             <table class="table text-center" style="font-size: 10pt; align: center">
                               <%= line_chart Historium.where(historiaid: current_user.id).order(mesfecha: :asc).pluck(:mesfecha, :rsbru) ,xtitle: "N° de encuesta", ytitle: "Puntaje ", width: "950px", height: "300px" , discrete: true , colors: ["#10a8ef"],  label: "Puntaje"%>
                             </table>
                           </div>
                         </div>

                     </div>
                     <%= link_to 'DESCARGAR PDF', historia_path(:format => :pdf ), :class => "btn btn-lg btn-success", :style=>"font-size: 15pt;left: 80%;  position: relative; "%>

                    </div>
              </div>

</div>
</div>
        </div>

</body>

resies/app/views/historia/new.html.erb
<h1>New Historium</h1>

<%= render 'form', historium: @historium %>

<%= link_to 'Back', historia_path %>

resies/app/views/historia/show.html.erb
<%= render 'form', historium: @historium %>