resies/config/routes.rb
Rails.application.routes.draw do

  resources :historia
  resources :questions
  resources :formularios
  resources :question
  resources :instituciones
  devise_for :users, controllers: {:registrations => 'user/registrations', :confirmations =>'user/confirmations'}
  root to: 'welcome#index'

  get 'manual/', to: 'manual#index'

  post'formularios/historia/:id',to:'formularios#historial' , as: 'historial'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

resies/app/models/alternativa.rb
class Alternativa < ApplicationRecord
  belongs_to :question
end

resies/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

resies/app/models/cat.rb
class Cat < ApplicationRecord
  has_many :subcats
end

resies/app/models/formulario.rb
class Formulario < ApplicationRecord

  belongs_to :user

end

resies/app/models/historium.rb
class Historium < ApplicationRecord
end

resies/app/models/institucione.rb
class Institucione < ApplicationRecord
  belongs_to :tipoinstitucione
  belongs_to :tiporelacione
  belongs_to :region

  has_attached_file :avatar, styles: { medium: "300x300", thumb: "50x50" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

resies/app/models/paise.rb
class Paise < ApplicationRecord
  has_many :regions
end

resies/app/models/question.rb
class Question < ApplicationRecord
  has_many :alternativas,  dependent: :destroy,  inverse_of: :question
  accepts_nested_attributes_for :alternativas,  allow_destroy: true
  belongs_to :subcat
end

resies/app/models/region.rb
class Region < ApplicationRecord
  has_many :instituciones
  belongs_to :paise
end

resies/app/models/subcat.rb
class Subcat < ApplicationRecord
  has_many :questions
  belongs_to :cat
end

resies/app/models/tipoinstitucione.rb
class Tipoinstitucione < ApplicationRecord
  has_many :instituciones
end

resies/app/models/tiporelacione.rb
class Tiporelacione < ApplicationRecord
  has_many :instituciones
end

resies/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :formularios
end

resies/app/controllers/instituciones_controller.rb
class InstitucionesController < ApplicationController
  before_action :set_institucione, only: [:show, :edit, :update, :destroy]

  # GET /instituciones
  # GET /instituciones.json
  def index
    @instituciones = Institucione.all
  end

  # GET /instituciones/1
  # GET /instituciones/1.json
  def show
    @instituciones = Institucione.all
  end

  # GET /instituciones/new
  def new
    @institucione = Institucione.new
    @instituciones = Institucione.all
  end

  # GET /instituciones/1/edit
  def edit
@instituciones = Institucione.all
  end

  # POST /instituciones
  # POST /instituciones.json
  def create
    @institucione = Institucione.new(institucione_params)
    @institucione.tipoinstitucione_id = 1
    @institucione.tiporelacione_id = 1
    @institucione.region_id = 1
    respond_to do |format|
      if @institucione.save
        format.html { redirect_to @institucione, notice: '' }
        format.json { render :show, status: :created, location: @institucione }
      else
        format.html { render :new }
        format.json { render json: @institucione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instituciones/1
  # PATCH/PUT /instituciones/1.json
  def update
    respond_to do |format|
      if @institucione.update(institucione_params)
        format.html { redirect_to @institucione, notice: '' }
        format.json { render :show, status: :ok, location: @institucione }
      else
        format.html { render :edit }
        format.json { render json: @institucione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instituciones/1
  # DELETE /instituciones/1.json
  def destroy
    @institucione.destroy
    respond_to do |format|
      format.html { redirect_to instituciones_url, notice: 'Institucione was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_institucione
      @institucione = Institucione.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institucione_params
      params.require(:institucione).permit(:nombre, :direccion, :codigopostal, :tipoinstitucione_id, :tiporelacione_id, :region_id,:avatar)
    end
end

resies/app/controllers/manual_controller.rb
class ManualController < ApplicationController
  def index
    @instituciones = Institucione.all
  end
end

resies/app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def javascript(*files)
  content_for(:head) { javascript_include_tag(*files) }
  end

def stylesheet(*files)
  content_for(:head) { stylesheet_link_tag(*files) }
end
def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end




end

resies/app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

resies/app/helpers/formularios_helper.rb
module FormulariosHelper
end

resies/app/helpers/historia_helper.rb
module HistoriaHelper
end

resies/app/helpers/instituciones_helper.rb
module InstitucionesHelper
end

resies/app/helpers/manual_helper.rb
module ManualHelper
end

resies/app/helpers/questions_helper.rb
module QuestionsHelper
end

resies/app/helpers/welcome_helper.rb
module WelcomeHelper
end

resies/app/views/instituciones/_form.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<%= javascript_include_tag "jr", "data-turbolinks-track" => true  %>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<hr>
<div class="container bootstrap snippet">
  <div id="user" class="col-md-12" >
  <%= form_with(model: institucione, local: true) do |form| %>
    <% if institucione.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(institucione.errors.count, "error") %> Prohibido que esta institución se guarde </h2>

        <ul>
        <% institucione.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
  		<div class="col-sm-10"><h2>Datos Institucionales </h2></div>
    </div>
    <div class="row">
  		<div class="col-sm-4"><!--left col-->
      <div class="text-center">
        <img src="<%= institucione.avatar.url(:medium)%>"  alt="avatar">
        <%= form.file_field :avatar %>
      </div></hr><br>
        </div><!--/col-3-->
    	<div class="col-sm-8">
          <div class="tab-content">
                  <form class="form" action="##" method="post" id="registrationForm">
                      <div class="form-group">
                          <div class="col-xs-6">
                              <label for="first_name"><h4>Nombre Institución</h4></label>
                              <%= form.text_field :nombre, id: :institucione_nombre, class:'form-control',placeholder:'Universidad Tecnologica Metropolitana' %>
                          </div>
                      </div>
                      <div class="form-group">

                          <div class="col-xs-6" >
                              <label for="email"><h4>Dirección</h4></label>
                          <%= form.text_field :direccion, id: :institucione_direccion, class:'form-control',placeholder:'Dieciocho 161, Santiago'%>
                          </div>
                      </div>
                      <div class="form-group">
                          <div class="col-xs-6">
                              <label ><h4>Tipo de Institución</h4></label>
                                <%= form.collection_select :tipoinstitucione_id, Tipoinstitucione.all, :id, :nombre , {include_blank: ''} , {class: 'form-control'}%>
                          </div>
                      </div>

                      <div class="form-group">
                          <div class="col-xs-6">
                             <label ><h4>Sistema de financiamiento</h4></label>
                             <%= form.collection_select :tiporelacione_id, Tiporelacione.all, :id, :nombre , {include_blank: ''} , {class: 'form-control'} %>
                      </div>

                      <div class="form-group">
                          <div class="col-xs-6">
                              <label ><h4>País</h4></label>
                              <%= form.collection_select :paise_id, Paise.all, :id, :nombre , {include_blank: ''} , {class: 'form-control'} %>
                          </div>
                      </div>
                      <div class="form-group">

                          <div class="col-xs-6">
                              <label><h4>Región</h4></label>
                               <%= form.grouped_collection_select :region_id, Paise.order(:nombre),:regions, :nombre, :id, :nombre , {include_blank: ''} , {class: 'form-control'}%>
                          </div>
                      </div>
                      <div class="form-group">

                          <div class="col-xs-6">
                            <label for="password2"><h4>Codigo Postal</h4></label>
                                <%= form.text_field :codigopostal, id: :institucione_codigopostal, class:'form-control',placeholder:'8320000'   %>
                          </div>
                      </div>
                      <div class="form-group">
                           <div class="col-xs-12">
                                <br>
                              	<button class="btn btn-lg btn-success" type="submit"><i class="glyphicon glyphicon-ok-sign"></i>Guardar</button>

                            </div>
                      </div>

              	</form>

        </div><!--/col-9-->
        <% end %>
    </div><!--/row-->
</div>
</div>
</div>
</div>
</body>

resies/app/views/instituciones/edit.html.erb
<% if @institucione.id == current_user.id %>
<body>

<%= render 'form', institucione: @institucione %>
</body>
<%else%>
<script>
    alert("Usted no puede editar otra institucion que no sea la propia");
    window.location.href=" /"
</script>
<%end%>

resies/app/views/instituciones/index.html.erb
 <%if current_user %>
 <%if current_user.rol == "admin"  %>
 <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<%= stylesheet_link_tag "mostrar.css" %>
<%= javascript_include_tag "mostrarins", "data-turbolinks-track" => true  %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/lumen/bootstrap.min.css">
<link rel="stylesheet" href="https://daneden.github.io/animate.css/animate.min.css">
<body>

<div class="container" style="margin-top:20px;">
<div class="row">
<div id="user" class="col-md-12" >
  <div class="panel panel-table " style="background-color: #E0FFFF" >
   <div class="panel-heading " style="padding:10px;">
     <div class="col col-xs-8 text-center">
            <p class="panel-title" style="font-size: 50pt" >Instituciones Adscritas</p>
        </div>
    </div>
   <div class="panel-body">
     <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="list">
       <table class="table table-striped table-bordered table-list">
        <thead>
         <tr>
            <th class="avatar"> </th>
            <th>Nombre</th>
            <th>Tipo de Institución</th>
            <th>País</th>
            <th><em class="fa fa-cog"></em></th>
          </tr>
         </thead>
         <tbody>
            <% @instituciones.each do |institucione| %>
            <tr class="ok">
            <td class="avatar"><img src="<%= institucione.avatar%>"></td>
            <td  align="center"><%= institucione.nombre %></td>
            <td  align="center"><%= institucione.tipoinstitucione.nombre %></td>
            <td  align="center"><%= institucione.region.paise.nombre %></td>
            <td align="center">
               <a><%= link_to 'Mostrar Datos ', institucione, :class => "btn btn-success" %></a>
                </td>
            </tr>
          <% end %>
        </tbody>
       </table>
       </div>
       </div>
       </div>
       </div>
       </div>
       </div>
       </div>
  <%else%>
</body>
    <script>
        alert("Usted no puede ingresar a esta dirección");
        window.location.href="/"
    </script>
    <%end%>
    <%else%>
    <script>
        alert("Usted no puede ingresar a esta dirección");
        window.location.href="/"
    </script>
    <%end%>

resies/app/views/instituciones/new.html.erb
<%if current_user %>
<%if current_user.rol == "admin"   %>
<p style="font-size: 50pt">Nueva Institución</p>

<%= render 'form', institucione: @institucione %>
<%else%>
<script>
    alert("Usted no puede ingresar a esta dirección");
    window.location.href="/"
</script>
<%end%>
<%else%>
<script>
    alert("Usted no puede ingresar a esta dirección");
    window.location.href="/"
</script>
<%end%>

resies/app/views/instituciones/pdf.pdf.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<%= stylesheet_link_tag "mostrar.css" %>
<%= javascript_include_tag "mostrarins", "data-turbolinks-track" => true  %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/lumen/bootstrap.min.css">
<link rel="stylesheet" href="https://daneden.github.io/animate.css/animate.min.css">
<body>

<div class="container" style="margin-top:20px;">
<div class="row">
<div id="user" class="col-md-12" >
  <div class="panel panel-table animated slideInDown" style="background-color: #E0FFFF" >
   <div class="panel-heading " style="padding:10px;">
     <div class="col col-xs-8 text-center">
            <p class="panel-title" style="font-size: 50pt" >Instituciones Adscritas</p>
        </div>
    </div>
   <div class="panel-body">
     <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="list">
       <table class="table table-striped table-bordered table-list">
        <thead>
         <tr>
            <th class="avatar"> </th>
            <th>Nombre</th>
            <th>Tipo de Institución</th>
            <th>País</th>
            <th><em class="fa fa-cog"></em></th>
          </tr>
         </thead>
         <tbody>
            <% @instituciones.each do |institucione| %>
            <tr class="ok">
            <td class="avatar"><img src="<%= institucione.avatar%>"></td>
            <td><%= institucione.nombre %></td>
            <td><%= institucione.tipoinstitucione.nombre %></td>
            <td><%= institucione.region.paise.nombre %></td>
            <td align="center">
               <a><%= link_to 'Mostrar Datos ', institucione, :class => "btn btn-success" %></a>
               <a><%= link_to 'Editar', edit_institucione_path(institucione) , :class => "btn btn-warning"%></a>
               <a><%= link_to 'Eliminar', institucione, method: :delete, data: { confirm: 'Esta seguro que desea eliminar esta institución?' }, :class => "btn btn-danger" %></a>
             </td>
            </tr>
          <% end %>

    </br></br>&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;
    <span class="	glyphicon glyphicon-edit" style="font-size: 20pt"><%= link_to 'Nueva Institución', new_institucione_path, class:'btn' %></span>

resies/app/views/instituciones/show.html.erb
<p id="notice"><%= notice %></p>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<%= javascript_include_tag "jr", "data-turbolinks-track" => true  %>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
<hr>
<div class="container bootstrap snippet">
  <div id="user" class="col-md-12" >
    <div class="row">
  		<div class="col-sm-10"><h2>Datos Institucionales </h2></div>
    </div>
    <div class="row">
  		<div class="col-sm-4"><!--left col-->
      <div class="text-center">
        <img src="<%= @institucione.avatar.url(:medium)%>"  alt="avatar">
      </div></hr><br>
        </div><!--/col-3-->
    	<div class="col-sm-8">
          <div class="tab-content">
                  <form class="form" action="##" method="post" id="registrationForm">
                      <div class="form-group">
                          <div class="col-xs-6">
                              <label ><h4>Nombre Institución</h4></label>
                              <p><%= @institucione.nombre %></p>
                          </div>
                      </div>
                      <div class="form-group">

                          <div class="col-xs-6">
                              <label ><h4>Dirección</h4></label>
                          <p><%= @institucione.direccion %></p>
                          </div>
                      </div>
                      <div class="form-group">

                          <div class="col-xs-6">
                              <label ><h4>Tipo de Institución</h4></label>
                              <p><%= @institucione.tipoinstitucione.nombre %><p>
                          </div>
                      </div>

                      <div class="form-group">
                          <div class="col-xs-6">
                             <label ><h4>Sistema de financiamiento</h4></label>
                             <p><%= @institucione.tiporelacione.nombre %></p>
                           </div>
                      </div>

                      <div class="form-group">
                          <div class="col-xs-6">
                              <label ><h4>País</h4></label>
                            <p><%= @institucione.region.paise.nombre %></p>
                          </div>
                      </div>
                      <div class="form-group">

                          <div class="col-xs-6" >
                              <label><h4>Región: </h4></label>
                              <p><%= @institucione.region.nombre %></p>
                          </div>
                      </div>
                      <div class="form-group">

                          <div class="col-xs-6">
                            <label><h4>Codigo Postal</h4></label>
                              <p><%= @institucione.codigopostal %></p>
                          </div>
                      </div>
                      <div class="form-group">
                           <div class="col-xs-12">
                                <td><%= link_to 'Editar', edit_institucione_path(@institucione), :class => "btn btn-success", :style =>"float: left;" %></td>

                            </div>
                      </div>

              	</form>

        </div><!--/col-9-->

    </div><!--/row-->
</div>
</hr>
</div>
</div>
</body>