resies/config/routes.rb
Rails.application.routes.draw do

  resources :historia
  resources :questions
  resources :formularios
  resources :question
  resources :instituciones
  devise_for :users, controllers: {:registrations => 'user/registrations', :confirmations =>'user/confirmations'}
  root to: 'welcome#index'

  get 'manual/', to: 'manual#index'

  post'formularios/historia/:id',to:'formularios#historial' , as: 'historial'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

resies/app/models/alternativa.rb
class Alternativa < ApplicationRecord
  belongs_to :question
end

resies/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

resies/app/models/cat.rb
class Cat < ApplicationRecord
  has_many :subcats
end

resies/app/models/formulario.rb
class Formulario < ApplicationRecord

  belongs_to :user

end

resies/app/models/historium.rb
class Historium < ApplicationRecord
end

resies/app/models/institucione.rb
class Institucione < ApplicationRecord
  belongs_to :tipoinstitucione
  belongs_to :tiporelacione
  belongs_to :region

  has_attached_file :avatar, styles: { medium: "300x300", thumb: "50x50" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

resies/app/models/paise.rb
class Paise < ApplicationRecord
  has_many :regions
end

resies/app/models/question.rb
class Question < ApplicationRecord
  has_many :alternativas,  dependent: :destroy,  inverse_of: :question
  accepts_nested_attributes_for :alternativas,  allow_destroy: true
  belongs_to :subcat
end

resies/app/models/region.rb
class Region < ApplicationRecord
  has_many :instituciones
  belongs_to :paise
end

resies/app/models/subcat.rb
class Subcat < ApplicationRecord
  has_many :questions
  belongs_to :cat
end

resies/app/models/tipoinstitucione.rb
class Tipoinstitucione < ApplicationRecord
  has_many :instituciones
end

resies/app/models/tiporelacione.rb
class Tiporelacione < ApplicationRecord
  has_many :instituciones
end

resies/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :formularios
end

resies/app/controllers/manual_controller.rb
class ManualController < ApplicationController
  def index
    @instituciones = Institucione.all
  end
end

resies/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.order("indicador").page(params[:page]).per(10)
    if params[:search]
      @questions = Question.search(params[:search]).order("created_at DESC").page(params[:page]).per(10)
      end
    @instituciones = Institucione.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @instituciones = Institucione.all
  end

  # GET /questions/new
  def new
    @instituciones = Institucione.all
    @question = Question.new
     @question.alternativas.build
    Rails.logger.debug("New method executed")

  end

  # GET /questions/1/edit
  def edit
    @instituciones = Institucione.all
    @alternativas= Alternativa.all
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:indicador, :pregunta, :tiporespuesta, :subcat_id,
      :alternativas_attributes => [:id, :nombre, :puntaje, :_destroy])
    end
end

resies/app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def javascript(*files)
  content_for(:head) { javascript_include_tag(*files) }
  end

def stylesheet(*files)
  content_for(:head) { stylesheet_link_tag(*files) }
end
def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end




end

resies/app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

resies/app/helpers/formularios_helper.rb
module FormulariosHelper
end

resies/app/helpers/historia_helper.rb
module HistoriaHelper
end

resies/app/helpers/instituciones_helper.rb
module InstitucionesHelper
end

resies/app/helpers/manual_helper.rb
module ManualHelper
end

resies/app/helpers/questions_helper.rb
module QuestionsHelper
end

resies/app/helpers/welcome_helper.rb
module WelcomeHelper
end

resies/app/views/questions/_alternativa_fields.html.erb
<fieldset>
  <label class="control-label "> Nombre : </label>
  <%= f.text_field :nombre , class:'form-control', placeholder:' Ej: Si, No, Otra Opción' %>

  <label class="control-label "> Puntaje : </label>

  <%= f.text_field :puntaje , class:'form-control', placeholder:' Ej: 0.8', :disabled=>true %>

</br></br>

</fieldset>

resies/app/views/questions/_form.html.erb
<%if current_user %>
<%if current_user.rol == "admin"  %>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<%= stylesheet_link_tag "preg.css" %>
<%= javascript_include_tag "pre", "data-turbolinks-track" => true  %>


<%= form_with(model: question, local: true) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container" style="padding-top:30px;">
    <div class="stepwizard" >
        <div class="stepwizard-row setup-panel" >
            <div class="stepwizard-step col-xs-6" >
                <a href="#step-1" type="button" class="btn btn-success btn-circle">1</a>
                <p><small>Pregunta</small></p>
            </div>
            <div class="stepwizard-step col-xs-6">
                <a href="#step-4" type="button" class="btn btn-default btn-circle" disabled="disabled">2</a>
                <p><small>Alternativas</small></p>
            </div>
        </div>
    </div>
        <div class="panel panel-default setup-content" id="step-1">
            <div class="panel-heading" style="background-color: #E0FFFF">
                 <h3 class="panel-title">Pregunta</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <label class="control-label">Indicador : </label>
                    <%= @question.indicador %>
                    </div>
                <div class="form-group">
                    <label class="control-label">Pregunta : </label>
                    <%= f.text_area :pregunta, id: :question_pregunta,  class:'form-control', placeholder:'Ej: Existen instancias de representatividad para el conjunto de estudiantes elegidas de forma democrática. Estas deben representar a la totalidad de los estudiantes de la institución. ' %>
                </div>

                <div class="form-group">
                        <label for="control-label">Categoria : </label>
                        <%= @question.subcat.cat.nombre%>
                </div>
                <div class="form-group">
                        <label for="control-label">SubCategoria :</label>
                        <%= @question.subcat.nombre %>
                </div>

                <div class="form-group">
                   <label class="control-label"> Tipo Respuesta :</label>
                    <%= @question.tiporespuesta %>
                    </div>
                <button class="btn btn-success  btn-lg nextBtn pull-right" type="button">Next</button>
            </div>

        </div>

        <div class="panel panel-default setup-content" id="step-4">
               <div class="panel-heading" style="background-color: #E0FFFF">
                    <h3 class="panel-title"> Alternativas</h3>
               </div>
                <div class="panel-body">
                  </br> </br>
                  <%= f.fields_for :alternativas do |alternativa| %>

                    <%= render 'alternativa_fields', f: alternativa %>

                  <%end%>
                  </br></br></br>
                 <button class="btn btn-success pull-right" type="submit">Finish!</button>
             </div>
         </div>
        </div>
    </form>
</div>
<%end%>
<%else%>
<script>
    alert("Usted no puede ingresar a esta dirección");
    window.location.href="/"
</script>
<%end%>
<%else%>
<script>
    alert("Usted no puede ingresar a esta dirección");
    window.location.href="/"
</script>


<%end%>

resies/app/views/questions/edit.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<p style="font-size: 35pt; margin-left: 40%; margin-top: 35px; font-style: italic; font-family: serif;">Editar Pregunta</p>


<%= render 'form', question: @question %>

resies/app/views/questions/index.html.erb
<%if current_user %>
<%if current_user.rol == "admin"  %>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<%= stylesheet_link_tag "mostrar.css" %>
<%= javascript_include_tag "mostrarins", "data-turbolinks-track" => true  %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/lumen/bootstrap.min.css">
<link rel="stylesheet" href="https://daneden.github.io/animate.css/animate.min.css">
<body>

<div class="container" style="margin-top:20px;">
<div class="row">
<div id="user" class="col-md-12" >
  <div class="panel panel-table " style="background-color: #E0FFFF" >
   <div class="panel-heading " style="padding:10px;">
     <div class="col col-xs-8 text-center">
            <p class="panel-title" style="font-size: 50pt" >Preguntas</p>
    </div>
    </div>
   <div class="panel-body">
     <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="list">
       <table class="table table-striped table-bordered table-list">
        <thead>
         <tr>
            <th>Indicador</th>
            <th>Pregunta</th>
            <th>Categoria</th>
            <th>Sub-Categoria</th>
            <th>Tipo Respuesta</th>
            <th><em class="fa fa-cog"></em></th>
          </tr>
         </thead>
         <tbody>
           <% @questions.each do |question| %>
             <tr class="ok">
               <td class="control-label col-xs-1"><%= question.indicador %></td>
               <td class="control-label col-xs-3"><%= question.pregunta %></td>
               <td class="control-label col-xs-2"><%= question.subcat.cat.nombre%></td>
               <td class="control-label col-xs-2"><%= question.subcat.nombre %></td>
               <td class="control-label col-xs-1"><%= question.tiporespuesta %></td>
               <td align="center">
                 <a><%= link_to 'Mostrar Datos ', question, :class => "btn btn-success" %></a>
                 <a><%= link_to 'Editar', edit_question_path(question) , :class => "btn btn-warning"%></a>
               </td>
             </tr>
           <% end %>


</tbody>
</table>
</div>
</div>
<div align= right style="marign:10px;">
<span  style="font-size: 18pt;"><%= paginate @questions %></span>
</div>
</div>
</div></div></div></div>
</body>
<%else%>
<script>
    alert("Usted no puede ingresar a esta dirección");
    window.location.href="/"
</script>
<%end%>
<%else%>
<script>
    alert("Usted no puede ingresar a esta dirección");
    window.location.href="/"
</script>


<%end%>

resies/app/views/questions/new.html.erb
<%if current_user %>
<%if current_user.rol != "admin"  && current_user.rol != "user"%>
<p style="font-size: 35pt; margin-left: 40%; margin-top: 35px; font-style: italic; font-family: serif;">Nueva Pregunta</p>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>
<%else%>
<script>
    alert("Usted no puede ingresar a esta dirección");
    window.location.href="/"
</script>
<%end%>
<%else%>
<script>
    alert("Usted no puede ingresar a esta dirección");
    window.location.href="/"
</script>


<%end%>

resies/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container" style=" font-family: monospace; margin-top: 60px;">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0" style="background-color: #E0FFFF">
                    <div class="row p-5" >
                        <div class="col-md-11 text-center" >
                            <p class="font-weight-bold mb-1" style="font-size: 35pt; font-family: monospace;">Pregunta</p>
                        </div>
                    </div>
                </div>


                    <div class="row pb-5 p-5" style="font-size: 12pt">
                        <div class="col-md-12">
                          <p>
                            <strong>Id:</strong>
                            <%= @question.id %>
                          </p>
                            <p>
                              <strong>Indicador:</strong>
                              <%= @question.indicador %>
                            </p>

                            <p>
                              <strong>Pregunta:</strong>
                              <%= @question.pregunta %>
                            </p>

                            <p>
                              <strong>Categoria:</strong>
                              <%= @question.subcat.cat.nombre%>
                            </p>

                            <p>
                              <strong>Subcategoria:</strong>
                              <%= @question.subcat.nombre %>
                            </p>
                            <p>
                              <strong>Tiporespuesta:</strong>
                              <%= @question.tiporespuesta %>
                            </p>
                        </div>
                    </div>

                    <div class="row p-5" >
                        <div class="col-md-12 text-center">
                            <table class="table text-center" style="font-size: 15pt">
                                <thead>
                                    <tr style="background-color: #E0FFFF">
                                        <th class="border-0 text-uppercase small font-weight-bold">ID</th>
                                        <th class="border-0 text-uppercase small font-weight-bold">Alternativa</th>
                                        <th class="border-0 text-uppercase small font-weight-bold">Puntaje</th>
                                    </tr>
                                </thead>
                                <tbody>

                                      <% for alternativa in @question.alternativas %>
                                      <tr>
                                           <td><%= alternativa.id %></td>
                                           <td><%= alternativa.nombre %></td>
                                           <td><%= alternativa.puntaje%></td>
                                      </tr>
                                       <% end %>
                                </tbody>
                            </table>
                          </br>

                          </br>
                        </div>
                          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &nbsp;&nbsp;&nbsp;&nbsp; &nbsp; <%= link_to 'Editar', edit_question_path(@question) , class: 'btn btn-success ', style:'font-size: 15pt; font-family: serif;' %>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                          &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
                          &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;   &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;   &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;   &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;   &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;   &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;

                          <%= link_to 'Volver', questions_path  , class: 'btn btn-warning', style:'font-size: 15pt; font-family: serif; ' %>
                    </div>
                </div>
            </div>
        </div>
    </div></br></br>